### ISSUE TITLE
Not working to set SMTP in fish shell

### ISSUE THREAD

**Issue by resonant-jovian** [quambene/pigeon-rs#3]
Hi,
Just wanted to try this out for some bulk emails and wanted to connect to gmail over smtp. 
When I use `SMTP_SERVER=smtp.gmail.com` I get this error: `fish: Unsupported use of '='. In fish, please use 'set SMTP_SERVER smtp.gmail.com'.`
I then use that command, aka `set SMTP_something something` for server username and password but when I go to `pigeon connect smtp` I get this error 
```
Error: Missing environment variable 'SMTP_SERVER'

Caused by:
    environment variable not found

```
My guess is that it is caused by me using fish for some reason.
And yes I did run `set -a && source .env && set +a` and yes the variables are set in the verbose output.

**Comment by resonant-jovian** [comment]
Tested with bash now and that works so the problem is when using fish.

**Comment by quambene** [comment]
Thanks for your bug report. Could you try the following commands?

- `set -x SMTP_SERVER smtp.gmail.com` instead of `SMTP_SERVER=smtp.gmail.com` in the `.env` file, and
- `source .env` instead of `set -a && source .env && set +a`
