### ISSUE TITLE
Is nightly toolchain still needed?

### ISSUE THREAD

**Issue by plavcik** [quambene/pigeon-rs#4]
I can't build this software on OpenBSD, as I can't switch to nightly toolchain. Is nightly toolchain still needed? Thank you, Jiří

**Comment by quambene** [comment]
Thanks for reporting, I will have a look

**Comment by quambene** [comment]
It's fixed on master branch, and I will create a new release in the coming days

**Comment by plavcik** [comment]
Great. Thank you, Jiří

**Comment by quambene** [comment]
Fixed in release v0.4.0
